# AUTO-GENERATED CONFIG
LOAD_PARAMS = { "Fx": 24000.0, "F_promien": 450.0, "L": 200.0, "w_Ty": 0.2, "w_Tz": 0.2 }
LISTA_MATERIALOW = ['S355']
MIN_SZEROKOSC_OTWARCIA = 70.0
MAX_GRUBOSC_PLASKOWNIKA = 25.0
SAFETY_PARAMS = { "gamma_M0": 1.0, "gamma_M1": 1.0, "alfa_imp": 0.49 }
NAZWA_BADANIA = ""
WSPOLNY_KATALOG = False
POKAZUJ_KROKI_POSREDNIE = False

# --- PARAMETRY STERUJĄCE OPTYMALIZACJĄ ---
START_SEARCH_OFFSET = 1
KROK_POSZERZANIA = 10.0
LIMIT_POSZERZANIA = 1.5
MAX_N_WZROSTOW_WAGI = 1
ILE_KROKOW_W_GORE = 2 # Domyślnie, można też dodać do GUI
SELECTED_SOLVER_MODULE = "solver_1_standard"
